import { useEffect, useRef, useState } from 'react'
import { TIER_META, RARITY_META, blockPriceFor, fmt, CASH_SYM, BLOCK_SYM } from './economy.js'
import { sfx } from './sound.js'

// The purchase agreement — a paper deed the player signs to close a deal.
// First purchase: draw a real signature (saved). After that: tap to affix it.

function SignaturePad({ onStroke }) {
  const canvasRef = useRef(null)
  const drawing = useRef(false)
  const empty = useRef(true)

  useEffect(() => {
    const c = canvasRef.current
    const dpr = window.devicePixelRatio || 1
    c.width = c.offsetWidth * dpr
    c.height = c.offsetHeight * dpr
    const ctx = c.getContext('2d')
    ctx.scale(dpr, dpr)
    ctx.strokeStyle = '#1d2f6b'
    ctx.lineWidth = 1.8
    ctx.lineCap = 'round'
    ctx.lineJoin = 'round'
  }, [])

  const pos = (e) => {
    const r = canvasRef.current.getBoundingClientRect()
    return [e.clientX - r.left, e.clientY - r.top]
  }

  function down(e) {
    e.preventDefault()
    canvasRef.current.setPointerCapture?.(e.pointerId)
    drawing.current = true
    const ctx = canvasRef.current.getContext('2d')
    const [x, y] = pos(e)
    ctx.beginPath()
    ctx.moveTo(x, y)
  }
  function move(e) {
    if (!drawing.current) return
    const ctx = canvasRef.current.getContext('2d')
    const [x, y] = pos(e)
    ctx.lineTo(x, y)
    ctx.stroke()
    if (empty.current) { empty.current = false }
  }
  function up() {
    if (!drawing.current) return
    drawing.current = false
    if (!empty.current) onStroke(canvasRef.current.toDataURL('image/png'))
  }

  return (
    <canvas
      ref={canvasRef}
      onPointerDown={down}
      onPointerMove={move}
      onPointerUp={up}
      onPointerLeave={up}
    />
  )
}

export default function Contract({ contract, playerName, signature, onComplete, onCancel }) {
  const [drawn, setDrawn] = useState(null)      // fresh signature dataURL
  const [affixed, setAffixed] = useState(false) // saved signature stamped
  const [padKey, setPadKey] = useState(0)       // clears the pad

  useEffect(() => { setDrawn(null); setAffixed(false); setPadKey(k => k + 1) }, [contract])

  if (!contract) return null
  const { poi, currency } = contract
  const meta = TIER_META[poi.tier] || TIER_META.shop
  const rar = RARITY_META[poi.rarity || 'common']
  const priceStr = currency === 'cash'
    ? `${CASH_SYM}${fmt(poi.price)}`
    : `${BLOCK_SYM}${fmt(blockPriceFor(poi.price))} $ESTATE`
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const signed = !!drawn || affixed
  const sigImage = drawn || (affixed ? signature : null)

  return (
    <div className="modal-backdrop" onClick={onCancel}>
      <div className="contract" onClick={e => e.stopPropagation()}>
        <div className="contract-inner">
          <div className="contract-kicker">Sol Estates Land Registry</div>
          <h2>Purchase Agreement</h2>
          <hr className="contract-rule" />
          <p>
            This agreement, executed on <span className="c-strong">{date}</span>, conveys full title of{' '}
            <span className="c-strong">{poi.name}</span> — a {rar.label.toLowerCase()} {meta.label.toLowerCase()} property —
            to <span className="c-strong">{playerName || 'the Bearer'}</span> for the agreed sum of{' '}
            <span className="c-strong">{priceStr}</span>.
          </p>
          <ul className="contract-clauses">
            <li>All rental income generated by the property accrues to the new owner from the moment of signing.</li>
            <li>The owner holds exclusive rights to improve, staff, or resell the property.</li>
            <li>Title is recorded permanently in the Sol Estates Land Registry.</li>
          </ul>

          <div className="sig-block">
            <div className="sig-label">Signature of the buyer</div>
            {signature && !drawn ? (
              affixed ? (
                <div className="sig-stamped"><img src={signature} alt="signature" /></div>
              ) : (
                <button
                  className="sig-pad"
                  style={{ width: '100%', font: 'inherit' }}
                  onClick={() => { sfx.sign(); setAffixed(true) }}
                >
                  <span className="sig-hint">Tap to affix your signature</span>
                </button>
              )
            ) : (
              <div className="sig-pad" key={padKey}>
                <SignaturePad onStroke={setDrawn} />
                {!drawn && <span className="sig-hint">Sign here with your mouse or finger</span>}
              </div>
            )}
            <div className="sig-line">
              <span className="sig-name">{playerName || 'The Bearer'}</span>
              <span className="sig-date">{date}</span>
            </div>
          </div>

          <div className="contract-actions">
            <button className="cancel" onClick={onCancel}>Decline</button>
            {!signature && drawn && (
              <button className="clear-sig" onClick={() => { setDrawn(null); setPadKey(k => k + 1) }}>Clear</button>
            )}
            <button
              className="sign-btn"
              disabled={!signed}
              onClick={() => { sfx.sign(); onComplete(sigImage) }}
            >
              {signed ? 'Complete Purchase' : 'Awaiting signature…'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
